### PR TITLE
[FR] Add Documentation on the available custom rules config options

### PR DESCRIPTION
**Pull request by eric-forte-elastic**
## Issues
https://github.com/elastic/DaC-Reference/issues/15

## Summary

This PR reconciles recent DAC feature updates with the local documentation in the detection rules repo as well as with the read the docs documentation. 

Primary new features added are additional config options for `bypass_version_lock` and `normalize_kql_keywords` the `exception_dir` support was already documented, just not implemented. 

Detection Rules PR: https://github.com/elastic/detection-rules/pull/3881

### CODE REVIEW

**Comment by eric-forte-elastic** [comment]
> Do you want to update the exception examples and the CLI commands to push/pull exception lists & merge this after those two PRs are in?

Yes, will do good idea and prevents the needs for an additional PR for this.

**Comment by eric-forte-elastic** [comment]
I added some quick start examples, but I do not think we have a place in the read the docs where we go over how to use the CLI commands. Should we add one? Or should we defer to the existing documentation in Detection Rules (e.g. CLI.md)?

**Review by Mikaayenson — APPROVED** [review]

**Comment by Mikaayenson** [comment]
Don't forget the example toml files for exception lists.

**Review by traut — APPROVED** [review]

**Comment by Mikaayenson** [comment]
@eric-forte-elastic I dont recall. Were you still planning to update the exception list example configs. Also would be good to add some the examples from the summary of your PR.

**Pull request merged**
